window.KAOS_SETTINGS_VIEW = (() => {
  function renderCustomEventSettings(deps) {
    const custom = deps.state.customEvents;
    const summary = [
      custom.marketDaysEnabled ? "Market Days" : "",
      custom.claimDayEnabled ? "Claim Day" : "",
    ].filter(Boolean).join(" + ") || "Disabled";
    const sync = custom.sync || {};
    const lastResult = sync.lastResult || sync;
    const syncTotal = Number(lastResult.total);
    const syncSummary = Number.isFinite(syncTotal)
      ? `${syncTotal} generated · ${Number(lastResult.unchanged || 0)} unchanged`
      : "Generated by KaosGovernor";
    const body = custom.loading && !custom.checked
      ? `<p class="taskMeta">Loading custom events...</p>`
      : custom.error
        ? `<div class="caregiverError"><span>${deps.escapeHtml(custom.error)}</span><button class="openButton" type="button" data-custom-events-retry>${deps.uiText("common.retry", "다시 시도")}</button></div>`
        : `
          <div class="settingsPolicyNote">
            <strong>Policy</strong>
            <span>KaosGovernor writes deterministic VEVENTs to Radicale. The LLM never owns these events.</span>
          </div>
          <dl class="customEventPolicy">
            <div>
              <dt>Market Day</dt>
              <dd>Every month on 5, 10, 15, 20, 25, and 30.</dd>
            </div>
            <div>
              <dt>Claim Day</dt>
              <dd>Every Friday. If Saturday is a market day, it moves to Saturday unless that date is a public holiday. Public holidays move it earlier.</dd>
            </div>
            <div>
              <dt>Sync</dt>
              <dd>${deps.escapeHtml(syncSummary)}</dd>
            </div>
          </dl>
          <div class="settingsPolicyNote">
            <strong>최근 동기화</strong>
            <span>${deps.escapeHtml(deps.generatedSyncSummary(custom.sync))}</span>
          </div>
          <div class="customEventSettingList">
            <label class="customEventSettingRow">
              <span><strong>Market Days</strong><small>Blue dot on 5, 10, 15, 20, 25, and 30</small></span>
              <input type="checkbox" data-custom-event-setting="marketDaysEnabled" ${custom.marketDaysEnabled ? "checked" : ""} ${custom.saving ? "disabled" : ""} />
            </label>
            <label class="customEventSettingRow">
              <span><strong>Claim Day</strong><small>Friday, adjusted for Market Saturday and public holidays</small></span>
              <input type="checkbox" data-custom-event-setting="claimDayEnabled" ${custom.claimDayEnabled ? "checked" : ""} ${custom.saving ? "disabled" : ""} />
            </label>
          </div>
          <div class="settingsActionRow">
            <button class="openButton" type="button" data-custom-events-sync ${custom.syncing ? "disabled" : ""}>
              ${custom.syncing ? "동기화 중..." : "생성 일정 동기화"}
            </button>
          </div>
        `;
    return `
      <details class="settingsDisclosure" data-custom-events ${custom.expanded ? "open" : ""}>
        <summary>
          <span><strong>Generated calendar events</strong><small>${deps.escapeHtml(summary)}</small></span>
        </summary>
        <div class="settingsDisclosureBody">${body}</div>
      </details>
    `;
  }

  function renderHolidaySettings(deps) {
    const holidays = deps.state.holidays;
    const publicCount = holidays.items.filter((item) => item.publicHoliday).length;
    const groups = holidays.items.reduce((result, item) => {
      const year = item.startDate.slice(0, 4) || deps.uiText("holidays.unknownYear", "Other");
      if (!result[year]) result[year] = [];
      result[year].push(item);
      return result;
    }, {});
    const body = holidays.loading && !holidays.checked
      ? `<p class="taskMeta">${deps.uiText("holidays.loading", "Loading Korean calendar...")}</p>`
      : holidays.error
        ? `<div class="caregiverError"><span>${deps.escapeHtml(holidays.error)}</span><button class="openButton" type="button" data-holidays-retry>${deps.uiText("common.retry", "다시 시도")}</button></div>`
        : holidays.items.length
          ? Object.keys(groups).sort().map((year) => `
              <section class="holidayYearGroup">
                <h3>${deps.escapeHtml(year)}</h3>
                <div class="holidaySettingList">
                  ${groups[year].map((item) => `
                    <label class="holidaySettingRow">
                      <span>
                        <time>${deps.escapeHtml(item.startDate.slice(5))}</time>
                        <strong>${deps.escapeHtml(item.title)}</strong>
                      </span>
                      <input
                        type="checkbox"
                        data-holiday-classification="${deps.escapeHtml(item.uid)}"
                        aria-label="${deps.escapeHtml(deps.uiText("holidays.publicHolidayAria", "Mark {title} as a public holiday", { title: item.title }))}"
                        ${item.publicHoliday ? "checked" : ""}
                      />
                    </label>
                  `).join("")}
                </div>
              </section>
            `).join("")
          : `<p class="taskMeta">${deps.uiText("holidays.none", "No Korean calendar entries imported yet.")}</p>`;
    return `
      <details class="settingsDisclosure" data-holidays ${holidays.expanded ? "open" : ""}>
        <summary>
          <span>
            <strong>${deps.uiText("holidays.title", "Korean calendar")}</strong>
            <small>${deps.uiText("holidays.summary", "{publicCount} public holidays · {total} entries", {
              publicCount,
              total: holidays.items.length,
            })}</small>
          </span>
        </summary>
        <div class="settingsDisclosureBody">
          <div class="holidaySettingsIntro">
            <p>${deps.uiText("holidays.help", "Checked dates are red public holidays. Unchecked entries remain dim calendar information.")}</p>
            <button class="openButton" type="button" data-holidays-sync ${holidays.syncing ? "disabled" : ""}>
              ${holidays.syncing ? deps.uiText("holidays.syncing", "Syncing...") : deps.uiText("holidays.sync", "Sync Google calendar")}
            </button>
          </div>
          ${body}
        </div>
      </details>
    `;
  }

  return { renderCustomEventSettings, renderHolidaySettings };
})();
