window.KAOS_SETTINGS_VIEW = (() => {
  function renderCustomEventSettings(deps) {
    const custom = deps.state.customEvents;
    const summary = [
      custom.marketDaysEnabled ? "Market Days" : "",
      custom.claimDayEnabled ? "Claim Day" : "",
    ].filter(Boolean).join(" + ") || "Disabled";
    const sync = custom.sync || {};
    const lastResult = sync.lastResult || sync;
    const syncTotal = Number(lastResult.total);
    const syncSummary = Number.isFinite(syncTotal)
      ? `${syncTotal} generated · ${Number(lastResult.unchanged || 0)} unchanged`
      : "Generated by KaosGovernor";
    const body = custom.loading && !custom.checked
      ? `<p class="taskMeta">Loading custom events...</p>`
      : custom.error
        ? `<div class="caregiverError"><span>${deps.escapeHtml(custom.error)}</span><button class="openButton" type="button" data-custom-events-retry>${deps.uiText("common.retry", "다시 시도")}</button></div>`
        : `
          <div class="settingsPolicyNote">
            <strong>Policy</strong>
            <span>KaosGovernor writes deterministic VEVENTs to Radicale. The LLM never owns these events.</span>
          </div>
          <dl class="customEventPolicy">
            <div>
              <dt>Market Day</dt>
              <dd>Every month on 5, 10, 15, 20, 25, and 30.</dd>
            </div>
            <div>
              <dt>Claim Day</dt>
              <dd>Every Friday. If Saturday is a market day, it moves to Saturday unless that date is a public holiday. Public holidays move it earlier.</dd>
            </div>
            <div>
              <dt>Sync</dt>
              <dd>${deps.escapeHtml(syncSummary)}</dd>
            </div>
          </dl>
          <div class="settingsPolicyNote">
            <strong>최근 동기화</strong>
            <span>${deps.escapeHtml(deps.generatedSyncSummary(custom.sync))}</span>
          </div>
          <div class="customEventSettingList">
            <label class="customEventSettingRow">
              <span><strong>Market Days</strong><small>Blue dot on 5, 10, 15, 20, 25, and 30</small></span>
              <input type="checkbox" data-custom-event-setting="marketDaysEnabled" ${custom.marketDaysEnabled ? "checked" : ""} ${custom.saving ? "disabled" : ""} />
            </label>
            <label class="customEventSettingRow">
              <span><strong>Claim Day</strong><small>Friday, adjusted for Market Saturday and public holidays</small></span>
              <input type="checkbox" data-custom-event-setting="claimDayEnabled" ${custom.claimDayEnabled ? "checked" : ""} ${custom.saving ? "disabled" : ""} />
            </label>
          </div>
          <div class="settingsActionRow">
            <button class="openButton" type="button" data-custom-events-sync ${custom.syncing ? "disabled" : ""}>
              ${custom.syncing ? "동기화 중..." : "생성 일정 동기화"}
            </button>
          </div>
        `;
    return `
      <details class="settingsDisclosure" data-custom-events ${custom.expanded ? "open" : ""}>
        <summary>
          <span><strong>Generated calendar events</strong><small>${deps.escapeHtml(summary)}</small></span>
        </summary>
        <div class="settingsDisclosureBody">${body}</div>
      </details>
    `;
  }

  return { renderCustomEventSettings };
})();
