const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const appSource = fs.readFileSync(path.join(__dirname, "../../apps/family-portal/app.js"), "utf8");
const smartEventsSource = fs.readFileSync(path.join(__dirname, "../../apps/family-portal/smart-events.js"), "utf8");
const indexSource = fs.readFileSync(path.join(__dirname, "../../apps/family-portal/index.html"), "utf8");
const styles = fs.readFileSync(path.join(__dirname, "../../apps/family-portal/styles.css"), "utf8");
const translations = fs.readFileSync(path.join(__dirname, "../../apps/family-portal/translations.js"), "utf8");

test("family calendar add defaults to smart preview while main stays manual", () => {
  assert.match(appSource, /addEventMode: portalProfile\(\) === "family" \? "smart" : "normal"/);
  assert.match(appSource, /function prepareAddEventRoute\(\)/);
  assert.match(appSource, /if \(portalProfile\(\) === "family"\) \{\s*state\.addEventMode = "smart";/);
  assert.match(appSource, /else if \(state\.addEventMode === "smart"\) \{\s*state\.addEventMode = "normal";/);
  assert.match(appSource, /if \(portalProfile\(\) !== "family" && state\.addEventMode === "smart"\) state\.addEventMode = "normal";/);
  assert.match(appSource, /runTopAddAction\(action\)[\s\S]*if \(action === "event"\) \{\s*prepareAddEventRoute\(\);/);
  assert.match(appSource, /enteringRoute && route === "add-event"\) prepareAddEventRoute\(\);/);
});

test("family smart event parser splits wife-style day text without saving", () => {
  assert.match(appSource, /function familySmartEventContext\(\)/);
  assert.match(appSource, /function parseFamilySmartEventInput\(value, dateValue = state\.selectedDate\)/);
  assert.match(appSource, /KAOS_FAMILY_SMART_EVENTS\.parseFamilySmartEventInput\(familySmartEventContext\(\), value, dateValue\)/);
  assert.match(smartEventsSource, /function normalizeFamilySmartEventTime\(hourValue, minuteValue, meridiem = ""\)/);
  assert.match(smartEventsSource, /if \(!marker && hour >= 1 && hour <= 7\) hour \+= 12;/);
  assert.match(smartEventsSource, /function splitFamilySmartEventInput\(value\)/);
  assert.match(smartEventsSource, /function parseFamilySmartEventInput\(deps, value, dateValue = deps\.state\.selectedDate\)/);
  assert.match(smartEventsSource, /splitFamilySmartEventInput\(value\)/);
  assert.match(smartEventsSource, /\\n/);
  assert.match(smartEventsSource, /그리고\|그다음\|그 다음\|다음\|또\|및/);
  assert.match(smartEventsSource, /\[\\\/\\n\+&\]\+/);
  assert.match(smartEventsSource, /function splitFamilySmartEventWeakComma\(value\)/);
  assert.match(smartEventsSource, /function familySmartEventCommaStartsNewEvent\(value\)/);
  assert.match(smartEventsSource, /current = `\$\{current\},\$\{part\}`;/);
  assert.match(smartEventsSource, /timeExpression = String\.raw/);
  assert.match(smartEventsSource, /embeddedTimePattern = new RegExp/);
  assert.match(smartEventsSource, /part\.match\(new RegExp/);
  assert.match(smartEventsSource, /const embeddedMatch = part\.match\(embeddedTimePattern\);/);
  assert.match(smartEventsSource, /part\.slice\(0, embeddedMatch\.index\)/);
  assert.match(smartEventsSource, /part\.slice\(embeddedMatch\.index \+ embeddedMatch\[0\]\.length\)/);
  assert.match(smartEventsSource, /allDay: true/);
  assert.ok(smartEventsSource.includes("(?:\\\\s*[-~–—]\\\\s*${timeExpression})?"));
  assert.match(smartEventsSource, /explicitEndTime = match\[6\]/);
  assert.match(smartEventsSource, /title = cleanFamilySmartEventTitle\(match\[9\] \|\| "", part\);/);
  assert.match(smartEventsSource, /explicitEndMinutes === null[\s\S]*deps\.addLocalMinutes\(dateValue, startTime, 60\)/);
  assert.match(smartEventsSource, /explicitEndMinutes <= startMinutes[\s\S]*deps\.addLocalMinutes\(dateValue, explicitEndTime, 24 \* 60\)/);
  assert.match(smartEventsSource, /function normalizeFamilySmartEventProposal\(deps, item, dateValue = deps\.state\.selectedDate\)/);
  assert.match(smartEventsSource, /function familySmartEventBaseProposals\(deps, dateValue = deps\.state\.selectedDate\)/);
  assert.match(smartEventsSource, /Array\.isArray\(deps\.state\.smartEventAiProposals\)/);
  assert.match(smartEventsSource, /function familySmartEventProposals\(deps, dateValue = deps\.state\.selectedDate\)/);
  assert.match(smartEventsSource, /familySmartEventBaseProposals\(deps, dateValue\)/);
  assert.match(smartEventsSource, /adjustFamilySmartEventEnd\(deps, item, Number\(deps\.state\.smartEventEndOffsets\[index\] \|\| 0\)\)/);
  assert.match(smartEventsSource, /function adjustFamilySmartEventEnd\(deps, item, minutes\)/);
  assert.match(smartEventsSource, /endMs <= startMs\) return item;/);
  assert.match(smartEventsSource, /function nextFamilySmartEventEndOffset\(deps, item, currentOffset, step\)/);
  assert.match(smartEventsSource, /currentEndMinutes % 60 !== 0/);
  assert.match(smartEventsSource, /stepMinutes = 60 - \(currentEndMinutes % 60\)/);
  assert.match(smartEventsSource, /if \(step < 0 && currentOffset > 0 && nextOffset < 0\) nextOffset = 0;/);
  assert.match(smartEventsSource, /function familySmartEventDurationMinutes\(item\)/);
  assert.match(smartEventsSource, /function formatFamilySmartEventDuration\(deps, item\)/);
  assert.match(smartEventsSource, /Math\.round\(\(endMs - startMs\) \/ 60_000\)/);
});

test("family smart event UI previews first and then saves with confirmation", () => {
  assert.match(appSource, /function renderFamilySmartEventPanel\(\)/);
  assert.match(appSource, /KAOS_FAMILY_SMART_EVENTS\.renderFamilySmartEventPanel\(familySmartEventContext\(\)\)/);
  assert.match(smartEventsSource, /data-family-smart-event-input/);
  assert.doesNotMatch(appSource, /event\.smartTextboxLabel/);
  assert.doesNotMatch(translations, /"event\.smartTextboxLabel"/);
  assert.match(smartEventsSource, /data-family-smart-event-preview/);
  assert.match(smartEventsSource, /renderFamilySmartEventPreview\(deps, proposals\)/);
  assert.match(smartEventsSource, /data-family-smart-event-ai-preview/);
  assert.match(smartEventsSource, /requestFamilySmartEventAiPreview\(deps\)/);
  assert.match(smartEventsSource, /fetch\("\/api\/calendar\/smart-events\/preview"/);
  assert.match(smartEventsSource, /useAi: true/);
  assert.match(smartEventsSource, /data-family-smart-event-save/);
  assert.match(smartEventsSource, /saveFamilySmartEvents\(deps\)/);
  assert.match(smartEventsSource, /window\.confirm\(familySmartEventSaveConfirmMessage\(deps, proposals\)\)/);
  assert.match(smartEventsSource, /deps\.postCalendarEvent\(payload\)/);
  assert.match(smartEventsSource, /window\.location\.hash = "#\/calendar";/);
  assert.match(smartEventsSource, /data-add-event-mode="normal"/);
  assert.match(appSource, /data-add-event-mode="smart"/);
  assert.match(smartEventsSource, /familySmartEventPreviewBody/);
  assert.match(smartEventsSource, /data-family-smart-event-end-step="-60"/);
  assert.match(smartEventsSource, /data-family-smart-event-end-step="60"/);
  assert.match(smartEventsSource, /data-family-smart-event-index="\$\{index\}"/);
  assert.match(smartEventsSource, /&lt;&lt;/);
  assert.match(smartEventsSource, /formatFamilySmartEventDuration\(deps, item\)/);
  assert.match(smartEventsSource, /&gt;&gt;/);
  assert.match(smartEventsSource, /item\.allDay \? deps\.uiText\("event\.allDayPill", "All Day"\) : `\$\{item\.startTime\}–\$\{item\.endTime\}`/);
});

test("family smart event input updates preview on input without rerendering the page", () => {
  const inputListener = appSource.match(/document\.addEventListener\("input", \(event\) => \{[\s\S]*?\n\}\);/);
  assert.ok(inputListener);
  assert.match(inputListener[0], /KAOS_FAMILY_SMART_EVENTS\.handleInput\(familySmartEventContext\(\), event\)/);
  assert.match(smartEventsSource, /data-family-smart-event-input/);
  assert.match(smartEventsSource, /deps\.state\.smartEventAiProposals = null;/);
  assert.match(smartEventsSource, /deps\.state\.smartEventAiError = "";/);
  assert.match(smartEventsSource, /deps\.state\.smartEventPreviewSource = "grammar";/);
  assert.match(smartEventsSource, /deps\.state\.smartEventEndOffsets = \{\};/);
  assert.match(smartEventsSource, /updateFamilySmartEventPreview\(deps\);/);
  assert.ok(smartEventsSource.includes('const saveButton = document.querySelector("[data-family-smart-event-save]");'));
  assert.match(smartEventsSource, /saveButton\.disabled = !proposals\.length \|\| deps\.state\.smartEventSaving;/);

  const changeListener = appSource.match(/document\.addEventListener\("change", async \(event\) => \{[\s\S]*?\n\}\);/);
  assert.ok(changeListener);
  assert.doesNotMatch(changeListener[0], /data-family-smart-event-input/);
});

test("family smart event assets include styling, translations, and cache busters", () => {
  assert.match(styles, /\.familySmartEventPanel \.panelBody \{/);
  assert.match(styles, /\.app\[data-profile="family"\] \.familySmartEventPanel textarea \{/);
  assert.match(styles, /width: 100%;/);
  assert.match(styles, /box-sizing: border-box;/);
  assert.match(styles, /resize: vertical;/);
  assert.match(styles, /font-family: inherit;/);
  assert.match(styles, /border-radius: 14px;/);
  assert.match(styles, /linear-gradient\(180deg, rgba\(255, 250, 255, 0\.86\), rgba\(244, 237, 248, 0\.92\)\)/);
  assert.match(styles, /\.familySmartEventPreview \{/);
  assert.match(styles, /\.familySmartEventControls \{/);
  assert.match(styles, /\.familySmartEventStep \{/);
  assert.match(styles, /\.familySmartEventDuration \{/);
  assert.match(styles, /\.familySmartEventPreviewBody \{/);
  assert.match(styles, /grid-column: 2;/);
  assert.match(translations, /"event\.smart": "스마트 입력"/);
  assert.match(translations, /"event\.smartPlaceholder": "연차\/10:30 3교시 참관수업 \/ 2:30 스파예가"/);
  assert.match(translations, /"event\.smartSave": "확인 후 저장"/);
  assert.match(translations, /"event\.smartSaving": "저장 중\.\.\."/);
  assert.match(translations, /"event\.smartAiPreview": "AI 정리"/);
  assert.match(translations, /"event\.smartSourceFallback": "AI를 사용할 수 없어 문법 미리보기를 사용했습니다\."/);
  assert.match(translations, /"dialog\.familySmartEventAiError": "AI 정리를 불러오지 못했습니다: \{error\}"/);
  assert.match(translations, /"dialog\.familySmartEventSaveConfirm": "미리보기 일정 \{count\}개를 캘린더에 저장할까요\?"/);
  assert.match(translations, /"event\.smartShorter": "1시간 줄이기"/);
  assert.match(translations, /"event\.smartLonger": "1시간 늘리기"/);
  assert.match(translations, /"event\.smartHoursSuffix": "시간"/);
  assert.match(translations, /"event\.smartMinutesSuffix": "분"/);
  assert.match(styles, /grid-template-columns: 96px minmax\(0, 1fr\);/);
  assert.match(indexSource, /href="\/styles\.css\?v=324"/);
  assert.match(indexSource, /src="\/translations\.js\?v=185"/);
  assert.match(indexSource, /src="\/smart-events\.js\?v=1"/);
  assert.ok(indexSource.indexOf('src="/smart-events.js?v=1"') < indexSource.indexOf('src="/app.js?v=334"'));
  assert.match(indexSource, /src="\/app\.js\?v=334"/);
});
