"""Calendar domain rules for KaosGovernor."""

from .adapter import (
    CalendarAdapterClient,
    CalendarAdapterConfig,
    CalendarAdapterError,
    portal_host,
    profile_host,
    route_allowed,
    upstream_url,
)
from .generated import (
    CLAIM_CATEGORY,
    GENERATED_CATEGORY,
    MARKET_CATEGORY,
    MARKET_DAYS,
    MARKET_SATURDAY_CATEGORY,
    SYSTEM_CATEGORY,
    GeneratedCalendarSettings,
    claim_date_for_friday,
    claim_event,
    claim_uid,
    claim_weeks,
    desired_events,
    event_matches,
    is_market_day,
    market_dates,
    market_event,
    market_uid,
    uid_year,
)

__all__ = (
    "CalendarAdapterClient",
    "CalendarAdapterConfig",
    "CalendarAdapterError",
    "CLAIM_CATEGORY",
    "GENERATED_CATEGORY",
    "MARKET_CATEGORY",
    "MARKET_DAYS",
    "MARKET_SATURDAY_CATEGORY",
    "SYSTEM_CATEGORY",
    "GeneratedCalendarSettings",
    "claim_date_for_friday",
    "claim_event",
    "claim_uid",
    "claim_weeks",
    "desired_events",
    "event_matches",
    "is_market_day",
    "market_dates",
    "market_event",
    "market_uid",
    "portal_host",
    "profile_host",
    "route_allowed",
    "uid_year",
    "upstream_url",
)
