from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from datetime import date, timedelta
import re
from typing import Any


SYSTEM_CATEGORY = "KAOS-SYSTEM"
GENERATED_CATEGORY = "KAOS-GENERATED-CALENDAR"
MARKET_CATEGORY = "KAOS-MARKET-DAY"
MARKET_SATURDAY_CATEGORY = "KAOS-MARKET-SATURDAY"
CLAIM_CATEGORY = "KAOS-CLAIM-DAY"
MARKET_DAYS = frozenset({5, 10, 15, 20, 25, 30})
GENERATED_MEMO = "Generated by KaosGDD Brain"
DEFAULT_WEATHER_LOCATION = "Pohang, KR"
DEFAULT_PUBLIC_HOLIDAY_REGION = "KR"
PUBLIC_HOLIDAY_PROVIDERS = frozenset({"manual", "imported", "disabled"})


def clean_text(value: object, default: str = "") -> str:
    text = str(value or "").strip()
    return text or default


@dataclass(frozen=True)
class GeneratedCalendarSettings:
    market_days_enabled: bool = True
    claim_day_enabled: bool = True
    weather_location: str = DEFAULT_WEATHER_LOCATION
    public_holiday_provider: str = "imported"
    public_holiday_region: str = DEFAULT_PUBLIC_HOLIDAY_REGION
    public_holiday_calendar_url: str = ""

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> "GeneratedCalendarSettings":
        provider = clean_text(
            value.get("publicHolidayProvider") or value.get("public_holiday_provider"),
            "imported",
        )
        if provider not in PUBLIC_HOLIDAY_PROVIDERS:
            provider = "imported"
        return cls(
            market_days_enabled=bool(value.get("marketDaysEnabled", value.get("market_days_enabled", True))),
            claim_day_enabled=bool(value.get("claimDayEnabled", value.get("claim_day_enabled", True))),
            weather_location=clean_text(
                value.get("weatherLocation") or value.get("weather_location"),
                DEFAULT_WEATHER_LOCATION,
            ),
            public_holiday_provider=provider,
            public_holiday_region=clean_text(
                value.get("publicHolidayRegion") or value.get("public_holiday_region"),
                DEFAULT_PUBLIC_HOLIDAY_REGION,
            ).upper(),
            public_holiday_calendar_url=clean_text(
                value.get("publicHolidayCalendarUrl") or value.get("public_holiday_calendar_url"),
            ),
        )

    def as_settings_payload(self) -> dict[str, object]:
        return {
            "marketDaysEnabled": self.market_days_enabled,
            "claimDayEnabled": self.claim_day_enabled,
            "weatherLocation": self.weather_location,
            "publicHolidayProvider": self.public_holiday_provider,
            "publicHolidayRegion": self.public_holiday_region,
            "publicHolidayCalendarUrl": self.public_holiday_calendar_url,
        }


def is_market_day(value: date) -> bool:
    return value.day in MARKET_DAYS


def dates_in_year(year: int) -> Iterable[date]:
    current = date(year, 1, 1)
    end = date(year + 1, 1, 1)
    while current < end:
        yield current
        current += timedelta(days=1)


def market_dates(year: int) -> list[date]:
    return [value for value in dates_in_year(year) if is_market_day(value)]


def claim_date_for_friday(friday: date, public_dates: Iterable[date] | None = None) -> date:
    public = set(public_dates or ())
    saturday = friday + timedelta(days=1)
    candidate = saturday if is_market_day(saturday) and saturday not in public else friday
    while candidate in public:
        candidate -= timedelta(days=1)
    return candidate


def claim_weeks(year: int, public_dates: Iterable[date] | None = None) -> list[tuple[date, date]]:
    first = date(year, 1, 1)
    friday = first + timedelta(days=(4 - first.weekday()) % 7)
    result = []
    while friday.year == year:
        result.append((friday, claim_date_for_friday(friday, public_dates)))
        friday += timedelta(days=7)
    return result


def market_uid(value: date) -> str:
    return f"KAOS-MARKET-{value.isoformat()}"


def claim_uid(friday: date) -> str:
    return f"KAOS-CLAIM-WEEK-{friday.isoformat()}"


def market_event(value: date) -> dict[str, object]:
    categories = [SYSTEM_CATEGORY, GENERATED_CATEGORY, MARKET_CATEGORY]
    if value.weekday() == 5:
        categories.append(MARKET_SATURDAY_CATEGORY)
    return {
        "uid": market_uid(value),
        "title": "Market Day",
        "memo": GENERATED_MEMO,
        "startDate": value.isoformat(),
        "endDate": value.isoformat(),
        "categories": categories,
    }


def claim_event(friday: date, value: date) -> dict[str, object]:
    return {
        "uid": claim_uid(friday),
        "title": "Claim Day",
        "memo": GENERATED_MEMO,
        "startDate": value.isoformat(),
        "endDate": value.isoformat(),
        "categories": [SYSTEM_CATEGORY, GENERATED_CATEGORY, CLAIM_CATEGORY],
    }


def desired_events(
    years: Iterable[int],
    public_dates: Iterable[date] | None,
    settings: GeneratedCalendarSettings | Mapping[str, Any],
) -> list[dict[str, object]]:
    resolved = settings if isinstance(settings, GeneratedCalendarSettings) else GeneratedCalendarSettings.from_mapping(settings)
    items: list[dict[str, object]] = []
    for year in sorted(set(years)):
        if resolved.market_days_enabled:
            items.extend(market_event(value) for value in market_dates(year))
        if resolved.claim_day_enabled:
            items.extend(claim_event(friday, value) for friday, value in claim_weeks(year, public_dates))
    return sorted(items, key=lambda item: (str(item["startDate"]), str(item["uid"])))


def normalized_categories(item: Mapping[str, Any]) -> list[str]:
    return sorted(str(value).strip().upper() for value in item.get("categories", []) if str(value).strip())


def event_matches(current: Mapping[str, Any], wanted: Mapping[str, Any]) -> bool:
    return (
        str(current.get("summary") or current.get("title") or "") == str(wanted["title"])
        and str(current.get("description") or current.get("memo") or "") == str(wanted["memo"])
        and str(current.get("startDate") or "") == str(wanted["startDate"])
        and str(current.get("endDate") or current.get("startDate") or "") == str(wanted["endDate"])
        and normalized_categories(current) == sorted(str(value) for value in wanted["categories"])
    )


def uid_year(uid: object) -> int | None:
    match = re.fullmatch(r"KAOS-(?:MARKET|CLAIM-WEEK)-(\d{4})-\d{2}-\d{2}", str(uid or "").upper())
    return int(match.group(1)) if match else None
